title: SER-Unimodal-Text-FineTuning-(${model.model_name})-(Loss-${loss.name})-(BS-${data.use_balanced_sampling})-(BS-Scheduler-${data.use_balanced_sampling_scheduler})-(FreezeBackbone-${model.freeze_backbone})-(LayerStrategy-${model.layer_weight_strategy})-(Pooling-${model.pooling_strategy})-(epochs-${trainer.max_epochs})-(bs-${train.batch_size})-(LR-${optimizer.params.learning_rate})

wandb_entity: alefiury

loss:
    name: "ce"
    gamma: 2.0
    alpha: 0.5
    use_weighted_loss: false # Uses "prior" weights as in https://www.isca-archive.org/odyssey_2024/chen24_odyssey.pdf

datasets:
    train:
        - name: Train
          metadata_path: "/hadatasets/alef.ferreira/SER/Interspeech/InterSpeech-SER-2025/Dataset/transcribed_canary_train_set.csv"
          base_dir: "/hadatasets/alef.ferreira/SER/Interspeech/Audios"
          filename_column: "FileName"
          transcript_column: "Transcript"
          speakeremb_base_dir: "/hadatasets/alef.ferreira/SER/Interspeech/TitaNet-large"
          target_column: "EmoClass"

    val:
        - name: Validation
          metadata_path: "/hadatasets/alef.ferreira/SER/Interspeech/InterSpeech-SER-2025/Dataset/transcribed_canary_validation_set.csv"
          base_dir: "/hadatasets/alef.ferreira/SER/Interspeech/Audios"
          filename_column: "FileName"
          transcript_column: "Transcript"
          speakeremb_base_dir: "/hadatasets/alef.ferreira/SER/Interspeech/TitaNet-large"
          target_column: "EmoClass"

data:
    num_classes: 8

    target_sr: 16000

    use_balanced_sampling: false # If true, the dataset will be balanced based on the inverse frequency of the classes
    use_balanced_sampling_scheduler: false # If true, the dataset will be balanced based on the inverse frequency of the classes, but the weights will be updated during training
    class_weight_direction: "to_uniform" # can be 'to_uniform' or 'to_distribution', this parameter is used to define the direction of the class weights
    class_weight_ratio_degree: 1 # 1 = linear, > 1 = polynomial

    # Text augmentation
    use_text_augmentation: false # If true, text augmentation will be used (random word deletion)
    text_augmentation_p: 0.0
    use_prompt: true
    prompt_text: "Represent the transcript for speech emotion recognition."

    # label2id must represent the names of the target in the metadata file
    label2id: {
        "A": 0,
        "C": 1,
        "D": 2,
        "F": 3,
        "H": 4,
        "N": 5,
        "S": 6,
        "U": 7
    }

train:
    batch_size: 32
    shuffle: True
    num_workers: 12

model:
    model_type: "dynamic_text"

    # model config
    model_name: "Qwen/Qwen3-Embedding-0.6B"
    freeze_backbone: false
    layer_weight_strategy: "per_layer"
    num_feature_layers: 28
    specific_layer_idx: -1
    pooling_strategy: "mean"

    # MLP config
    mlp_input_dim: 1024 # Must be adapted to the model, when using attention pooling, this value should be the double of the model hidden size
    mlp_hidden_dim: ${model.mlp_input_dim} # Must be adapted to the model, should be the same as mlp_input_dim
    mlp_num_layers: 1
    mlp_output_size: ${data.num_classes}
    mlp_dropout: 0.1
    mlp_activation_func: "relu"

optimizer:
    name: "adamw"
    params:
        min_learning_rate: 1e-5 # Same used in https://ecs.utdallas.edu/research/researchlabs/msp-lab/publications/Goncalves_2024.pdf
        learning_rate: 5e-5 # Same used in https://ecs.utdallas.edu/research/researchlabs/msp-lab/publications/Goncalves_2024.pdf
        eps: 1e-8
        weight_decay: 1e-6
        betas: [0.9, 0.98]

scheduler:
    name: "CosineWarmupLR"
    params:
        warmup_lr: 500

tags:
    - ${train.batch_size}-BS
    - LR-${optimizer.params.learning_rate}
    - WD-${optimizer.params.weight_decay}
    - BS-${data.use_balanced_sampling}
    - ${model.mlp_input_dim}-AH
    - ${model.mlp_hidden_dim}-HL
    - ${model.mlp_num_layers}-IS

trainer:
    accelerator: "gpu"
    max_epochs: 20
    num_sanity_val_steps: 2
    overfit_batches: 0.0
    log_every_n_steps: 10
    gradient_clip_val: 10.0
    gradient_clip_algorithm: "norm"
    val_check_interval: 1.0
    accumulate_grad_batches: 1
    reload_dataloaders_every_n_epochs: 0 # This should be set to 1 if "data.use_balanced_sampling_scheduler" is True

model_checkpoint:
    mode: "max"
    save_last: true
    save_weights_only: true
    monitor: "val/f1-score"
    dirpath: "../checkpoints/ser-2025"
    filename: "{epoch:02d}-{step:02d}-{val/f1-score:.4f}"